#TODO: Finish the gcc call needed to compile your program
#	   Then you can compile your code with just 'make' or 'make puppies'
puppies: main.c puppies.c #TODO: Add required .c files to this line
	gcc main.c puppies.c
