#include "draw.h"
#include "gba.h"

//Author: Jared Raiola
//GTID: 903293358

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(BLACK); // set backgroud
    drawImageDMA(state -> ship.xPos, state -> ship.yPos, PSHIP_WIDTH,
    	PSHIP_HEIGHT, pShip); //draw ship in initial positions
    drawRectDMA(0, 0, 240, 10, WHITE); // draw area for score and wave counter
    char newScore[40]; // create scorecard string
    sprintf(newScore, "SCORE: 0"); //initialize it to 0
    drawString(2, 2, newScore, BLACK); // draw in top left
    drawString(WIDTH / 3 - 5, 30, "PRESS A TO FIRE", RED); // next three lines draw game instructions
    drawString(WIDTH / 5 - 40, 45, "PRESS LEFT,RIGHT, UP AND DOWN TO MOVE", RED);
    drawString(WIDTH / 5 - 20, 60, "MOVE IN ANY DIRECTION TO BEGIN", RED);
    drawString(220, 2, "WAVE 1", BLACK); // draw wave counter top right
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
	if (state -> startGame == 9) {
		drawRectDMA(0, 11, 240, 90, BLACK); // wait until game begins (after player reads instructions) and then cover instructions
	}
	drawRectDMA(0, 0, 240, 10, WHITE); // refresh scorecard area
	drawRectDMA(0, state -> ship.yPos, WIDTH,
    	PSHIP_HEIGHT, BLACK); // undraw ship
	drawRectDMA(state -> fireball.xPos, state -> fireball.yPos, PROJ_WIDTH,
    	PROJ_HEIGHT, BLACK); // undraw fireball
	if (state -> alienGone == 1) {
		drawRectDMA(state -> alien.xPos, state -> alien.yPos, ENEMY_WIDTH,
    	ENEMY_HEIGHT, BLACK); // undraw alien
	}
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawImageDMA(state -> ship.xPos, state -> ship.yPos, PSHIP_WIDTH,
    	PSHIP_HEIGHT, pShip); // draw ship in new position
    if (state -> startGame < 10) {
    	char newScore[40]; // draw scorecard before game starts
	    sprintf(newScore, "SCORE: 0");
	    drawString(2, 2, newScore, BLACK);
    }
    if (state -> moveTimer > 15000) {
    	drawString(183, 2, "LAST WAVE", BLACK); // only draw when past frame 15000, this is when you're at the final wave
    } else if (state -> moveTimer > 10000) {
    	drawString(200, 2, "WAVE 3", BLACK); // same deal but at frame 10000
    } else if (state -> moveTimer > 5000) {
    	drawString(200, 2, "WAVE 2", BLACK); // "" 5000
    } else {
    	drawString(200, 2, "WAVE 1", BLACK); // draw for beginning wave
    }
    if (state -> startGame > 9 && state -> alienGone == 0) {
	    drawImageDMA(state -> alien.xPos, state -> alien.yPos, ENEMY_WIDTH, 
	    	ENEMY_HEIGHT, alien); // draw alien only when game begins
	    drawRectDMA(state -> alien.xPos, state -> alien.yPos - 2, ENEMY_WIDTH, 5, BLACK); // prevents green trail behind alien
	    char scoreString[40]; // update scorecard
	    sprintf(scoreString, "SCORE: %d", state -> gameScore);
	    drawString(2, 2, scoreString, BLACK);
    }

    if (state -> ship.fire == 1) {
    	drawImageDMA(state -> fireball.xPos, state -> fireball.yPos, PROJ_WIDTH, 
        PROJ_HEIGHT, fireball); // if the ship fired, move fireball
    }
}
